<html>
<head>
    <title>HTML Forms</title>
</head>
<body style="background-color:lightgray">


    <center>
        <h2>HTML Forms</h2>      
        <form>

            First name:<br>
            <input type="text" name="firstname" value="Akshada"><br><br>

            Last name:<br>
            <input type="text" name="lastname" value="Kangane"><br><br>
            <img src="HTML.jpg" width="50">
            <input type="radio" name="language"> HTML<br>
            <img src="CSS.webp" width="50">
            <input type="radio" name="language"> CSS <br>
            <img src="JS.png" width="50">
            <input type="radio" name="language"> JavaScript <br><br>

            <input type="checkbox"> I have a bike <br>
            <input type="checkbox"> I have a car <br>
            <input type="checkbox"> I have a boat <br><br>

            <input type="submit" value="Submit">
        </form>
    </center>
        <h2>Contact Information</h2>
        <p><b><u>name:</u></b><i>Akshada B. Kangane</i></p>
        <address>
            met indtute of trchnology adgoan nashik<br />
            department of information tecgnology<br />
            name :akshada balu kangane<br />
            email:ictabk@gmail.com<br />
            phone:8743785734
        </address>
 
</body>
</html>